### PR TITLE
Added Egress Outbound Variable & Updated Redis Family in Example

### PR DESCRIPTION
**Pull request by barissekerciler**
## what
* Added cidr block option to egress traffic (default is 0.0.0.0/0)
* Updated example with Redis 6.x

## why
* Business case (PCI-DSS). If you want to put Redis cluster to the private subnet, it shouldn't outbounds traffic to the all. At least, for a module, it must be opitonal.

### CODE REVIEW

**Review by osterman — APPROVED** [review]

**Review by joe-niland — APPROVED** [review]

**Comment by joe-niland** [comment]
@barissekerciler thanks for your contribution!

**Pull request merged**
