### PR TITLE
Allow empty "egress_cidr_blocks"

### PR DESCRIPTION
**Pull request by marcuz**
## what
* Allow empty `egress_cidr_blocks` (no egress rules in default security group)

## why
* Not mandatory to have an egress rule

## references
*  #90

### CODE REVIEW

**Comment by marcuz** [comment]
@adamcrews @brcnblc any chance to get some love on this please? :smiley:

**Comment by marcuz** [comment]
@Gowiem apologies to include you, any chance someone can have a look at this?

**Review by Gowiem — APPROVED** [review]

**Review by Gowiem — APPROVED** [review]

**Pull request merged**
