### PR TITLE
feat: add support for using existing parameter group

### PR DESCRIPTION
**Pull request by bkero**
## what

Allows an existing parameter group to be specified. This is useful for cases where you simply want to use an existing parameter group (such as `default.redis7`), or when a parameter group is handled in other places within Terraform.

## why

We have some clusters which are using existing parameter groups who's management is out of scope for this module. We would like to use them with clusters deployed using this module.

### CODE REVIEW

**Comment by y3ti** [comment]
Duplicated https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/208

**Comment by bkero** [comment]
Hey there. I just read #208 and it that it has a similar goal, although still enforces creation of a parameter group. The impetus for this pull request is to allow an already-existing parameter group to be specified. If you look at the `count` metaparameter of the `parameter_group` resource, you'll see that I'm preventing the creation if a name is specified.

**Comment by bkero** [comment]
> Duplicated #208

Hey there. I just read https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/208 and it that it has a similar goal, although still enforces creation of a parameter group. The impetus for this pull request is to allow an already-existing parameter group to be specified. If you look at the count metaparameter of the parameter_group resource, you'll see that I'm preventing the creation if a name is specified.

**Comment by y3ti** [comment]
@bkero ach ok, you are right. Thank you for explaining it once more :) 

What if we have a new variable `create_parameter_group`? If the variable's value is set to `false` then the parameter group won't be created. If set to `true` then the new parameter group will be created with the name set to `${parameter_group_name}`. This approach allows us to address both scenarios effectively.

**Comment by bkero** [comment]
> @bkero ach ok, you are right. Thank you for explaining it once more :) 
> 
> What if we have a new variable `create_parameter_group`? If the variable's value is set to `false` then the parameter group won't be created. If set to `true` then the new parameter group will be created with the name set to `${parameter_group_name}`. This approach allows us to address both scenarios effectively.
> 
> 

Yes I would find that perfectly satisfactory. It would allow me to use the default `default.redis7` parameter group.

**Comment by y3ti** [comment]
@bkero I added the new variable `create_parameter_group` to my PR: https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/208#issuecomment-1834618174

**Pull request closed without merging**
