### PR TITLE
feat: Allow configuring auth_token_update_strategy

### LINKED ISSUE #55: Add auth_token_update_strategy option
Currently, any auth_token changes are destroying and are recreating Redis cluster.

AWS API has option to set new token and chose update strategy: SET or ROTATE

https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ModifyCacheCluster.html

### PR DESCRIPTION
**Pull request by amontalban**
## what

Allow configuring `auth_token_update_strategy` provider setting.

This has been added to [AWS Provider on v5.27.0](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5270-november-27-2023) in this PR https://github.com/hashicorp/terraform-provider-aws/pull/16203

## why

Give user the flexibility to change the update strategy when setting/changing the `auth_token`.

## references

Closes #55

### CODE REVIEW

**Comment by gberenice** [comment]
@amontalban thanks for your contribution! Could you please bump [the AWS provider version](https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/main/versions.tf#L7) to `5.2.70` so the constraint reflects the version where this setting was actually added?

**Comment by Laakso** [comment]
@amontalban I guess this is almost done apart from the bumping the provider version? I am also blocked by this. Thanks!

**Comment by amontalban** [comment]
@gberenice @Laakso sorry I missed your messages, I have just pushed the change for the provider version.

Thanks for reviewing it!

PS: If you have time I would like to merge #231 too.

**Review by gberenice — APPROVED** [review]
@amontalban LGTM, thanks!

**Pull request merged**
