### PR TITLE
Adding ability to encrypt redis at rest and ability to enable TLS for…

### PR DESCRIPTION
**Pull request by mntechguy**
## what
* Set flags to enable encryption at rest and in transit.  Default to false for backwards compatibility.
* Fix regression with not setting availability_zones to [] by default

## why
* PCI / HIPAA compliance

### CODE REVIEW

**Comment by mntechguy** [comment]
Let me know if you need me to do anything else to contribute, basically just trying to get flags for enabled encryption at rest, and enabling TLS

**Comment by osterman** [comment]
@mntechguy would try running the following to update the `README.md`?

```
make init
make readme/deps
make readme
```

**Comment by mntechguy** [comment]
@osterman Ah, forgot to commit the variable file change as well.  Fixed both things.

**Comment by osterman** [comment]
@mntechguy looks like we've introduced a regression that wasn't caught by CI b/c travis wasn't enabled. It's not your fault. 

Can you fix this while you're at it:

https://github.com/mntechguy/terraform-aws-elasticache-redis/blob/018ef5f09d8b036f31b18f3326ec0562d435ffc5/variables.tf#L112

https://travis-ci.org/cloudposse/terraform-aws-elasticache-redis

**Comment by osterman** [comment]
It should be
```
default     = []
```

**Comment by mntechguy** [comment]
@osterman Added.

**Comment by osterman** [comment]
@mntechguy thx! looks like linting is failing on `variables.tf`

run `terraform fmt .`

**Pull request merged**
