### PR TITLE
Change az parameter to preferred_cache_cluster_azs

### PR DESCRIPTION
**Pull request by odie5533**
https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/173

## what
The module should use [preferred_cache_cluster_azs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_replication_group#preferred_cache_cluster_azs) in the aws_elasticache_replication_group.

## why
This would allow us to specify the preferred primary node. Also the parameter used for AZs, availability_zones, is deprecated.

## references
https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/173

### CODE REVIEW

**Comment by smelchior** [comment]
@odie5533 could you update the pull request :)?
As the tf aws provider in 5.0.0 now removed the availability_zones option the module currently breaks with that version, so it would be nice to update this.

**Comment by odie5533** [comment]
> @odie5533 could you update the pull request :)? As the tf aws provider in 5.0.0 now removed the availability_zones option the module currently breaks with that version, so it would be nice to update this.

Rebased off the new changes 👍

**Review by muhammadasgharaliqureshi — APPROVED** [review]
LGTM

**Comment by rajatrj16** [comment]
This is a breaking change - pls merge this.

**Comment by milldr** [comment]
already merged with #198

**Pull request closed without merging**
