### PR TITLE
Add variables for parameter_group_name and parameter_group_create_on_destroy

### PR DESCRIPTION
**Pull request by joshuabaird**
## what
This PR adds two new variables:
* `parameter_group_name`
* `parameter_group_create_before_destroy`

## why
This module doesn't currently support major version upgrades of Redis (eg, 6.x to. 7.x) because:
* Parameter groups are major-version specific, so when a user changes `var.family` from `redis6` to `redis7`, Terraform needs to create a new parameter group.  Without `create_before_destroy`, Terraform tries to first destroy the old Param group which fails because it's currently in use 
* Parameter groups must have unique names across families.  When Terraform tries to create a new param group for `redis7`, it fails because it tries to do so using the same name as the old param group.

## references
* Closes https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/178

### CODE REVIEW

**Comment by joshuabaird** [comment]
Can we get this merged?

**Comment by joshuabaird** [comment]
> @joshuabaird thanks for the PR Please see the errors https://github.com/cloudposse/actions/actions/runs/4376943663/jobs/7659766652
> 
> variables are not allowed in the `lifecycle` block. This is an annoying TF feature We usually get around that by creating two similar resources

I see that Terratest is failing, but this code _does_ work.  I'm using it.  I'll take a look at your suggestion.

**Comment by goruha** [comment]
@joshuabaird Yes. We have so issue with our test infrastructure.
I will rerun tests ASAP.

**Comment by joshuabaird** [comment]
Thinking about this more, I don't think we need to parameterize the lifecycle in the first place.  I think this is easily solved by always setting `create_before_destroy = true`.

**Pull request closed without merging**
