### PR TITLE
fix: remove transit_encryption != null, auth_token rotation support

### LINKED ISSUE #194: random_password as auth_token rotation causes destroy and create because of transit_encryption handling != nuill
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
If one tries to set a new dynamic `auth_token` the way this module is written it will cause a destroy and create of the redis cache. The upstream aws provider added this support [here](https://github.com/hashicorp/terraform-provider-aws/pull/16203). 

The way [transit_encryption_enabled](https://github.com/cloudposse/terraform-aws-elasticache-redis/blob/master/main.tf#L137) is handled causes a destroy create when the `auth_token` is changed with a `random_password` as a source. Any dynamic input for auth_token causes this, a string literal will not replicate this issue. Because a string literal will be known at plan time. The work around with `random_password` has to be in state for us to get good modify only behavior.

Because the conditional `var.transit_encryption_enabled || var.auth_token != null` when auth_token is rotated but not yet known, terraform assumes the worst and I believe this causes the destroy create. (Credits to `apparentlymart` in the hangops slack. [Thread here](https://hangops.slack.com/archives/C0Z93TPFX/p1682346440920649)) 

## Expected Behavior
Using `random_password` to generate an `auth_token` and rotating it, I expected the redis cache to be modified not, destroy/created again. This is more disruptive than it has to be.

## Steps to Reproduce
See this [gist](https://gist.github.com/Steve-Louie-Bose/937dec8b429450889454362cb2dd2bd5) as a reference.
1. Apply `random_password.password`, `aws_elasticache_replication_group.default` and `module.redis`.
2. At the same time uncomment the code for `random_password.password2` and use it in both redis blocks. (you'll see the resource works fine where the module destroy creates.)
   - the key to the above is in the same plan/apply phase we have to be adding a dynamic auth_token value which isn't fully known at plan time.
3. You'll see the redis cache get destroyed and recreated

--- 
The work around with the code as it is written is:
1. Apply `random_password.password`, `aws_elasticache_replication_group.default` and `module.redis`.
2. Plan and apply just `random_password.password2` but do not reference it in the redis blocks. 
3. Once `password2` is known in state, use it as the `auth_token` in both redis blocks
4. this will only modify the cache instead of destroy create because the `auth_token` will be fully known since it's in the state.

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):
OSX
terraform 1.3.1
aws provider 4.63.0
random provider 3.5.1

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

### PR DESCRIPTION
**Pull request by Steve-Louie-Bose**
## what
* This conditional causes this module to not support dynamic auth_token rotation in a nice way. This conditional forces us into a destroy/create instead of an in place modify

## why
* Avoiding a destroy / create when the aws providers supports this behavior is worth it. It would allow one to use `random_password` and feed that into an `auth_token` and rotate it gracefully.

## references
- closes #194

### CODE REVIEW

**Comment by gusse** [comment]
I guess this isn't going to be merged?

**Comment by Gowiem** [comment]
@gusse not necessarily. This seems like a valid change... we just get a TON of PRs and a lot of the module PR review is done by volunteers (myself included). That said... are you using @Steve-Louie-Bose's fork? Can you confirm it works as you would expect?

**Comment by gusse** [comment]
> @gusse not necessarily. This seems like a valid change... we just get a TON of PRs and a lot of the module PR review is done by volunteers (myself included). That said... are you using @Steve-Louie-Bose's fork? Can you confirm it works as you would expect?

No worries, I understand there are tons of things to do and I do appreciate your hard work, thank you for that 🙏 Was just wondering if more is needed where I could possibly help

I'm indeed using @Steve-Louie-Bose's fork+branch and it seems to be working as expected. In my scenario, I'm updating the module from `0.41.1` to `1.2.0` and the problem was that cluster recreation is forced as I have the `auth_token` defined.

**Comment by Gowiem** [comment]
@gusse good to know, thanks for the double check. On these "random removal of logic" PRs, we don't typically have the context of why that might be there, so it can be scary change. Considering it's working for both of you though... I'm inclined to say we move it forward. 

@Steve-Louie-Bose unfortunately, we need to run some automation to pass our tests. Mind doing the following locally, adding + committing the result, and pushing to your branch?

```
make init
make readme
```

Once you do that, ping me and I'll provide a review. Thanks!

**Comment by Steve-Louie-Bose** [comment]
@Gowiem and @gusse  - updated the readme following your instructions

**Comment by Steve-Louie-Bose** [comment]
@gusse - I did post a work around that should work for you. You'd need to define your auth_token in state first and then run a follow up TF plan that can swap the value in place without destroy/create.

**Review by Gowiem — APPROVED** [review]
LGTM

**Pull request merged**
