### PR TITLE
Allow Module to Disable or Enable Cluster Mode for Existing Deployment

### LINKED ISSUE #180: Cannot Disable Cluster Mode
## Describe the Bug
If the module is already deployed with cluster mode enabled, attempting to modify the deployment to disable cluster mode will fail

## Expected Behavior
The cluster should be able to be modified to non-cluster mode 

## Steps to Reproduce
Deploy the resource with cluster mode enabled, via
```
cluster_mode_enabled = true
cluster_mode_num_node_groups = 3
cluster_mode_replicas_per_node_group = 2
```

Now disable cluster mode and redeploy
```
cluster_mode_enabled = false
cluster_mode_num_node_groups = 0
cluster_mode_replicas_per_node_group = 0
```

## Screenshots
```
╷
│ Error: Invalid function argument
│
│   on .terraform/modules/redis_clusters.redis/main.tf line 223, in module "dns":
│  223:   records  = var.cluster_mode_enabled ? [join("", aws_elasticache_replication_group.default.*.configuration_endpoint_address)] : [join("", aws_elasticache_replication_group.default.*.primary_endpoint_address)]
│     ├────────────────
│     │ while calling join(separator, lists...)
│     │ aws_elasticache_replication_group.default is tuple with 1 element
│
│ Invalid value for "lists" parameter: element 0 is null; cannot concatenate null values.
╵
╷
│ Error: Invalid function argument
│
│   on .terraform/modules/redis_clusters.redis/outputs.tf line 22, in output "endpoint":
│   22:   value       = var.cluster_mode_enabled ? join("", aws_elasticache_replication_group.default.*.configuration_endpoint_address) : join("", aws_elasticache_replication_group.default.*.primary_endpoint_address)
│     ├────────────────
│     │ while calling join(separator, lists...)
│     │ aws_elasticache_replication_group.default is tuple with 1 element
│
│ Invalid value for "lists" parameter: element 0 is null; cannot concatenate null values.
╵
Releasing state lock. This may take a few moments...
exit status 1
```

## Environment (please complete the following information):
- [terraform-aws-elasticache-redis](https://github.com/cloudposse/terraform-aws-elasticache-redis) v 0.46.0
- Terraform v 1.3.0
- hashicorp/aws v4.38.0

### PR DESCRIPTION
**Pull request by milldr**
## what
- added compact for when resource dne

## why
- Currently, if the module is deployed with cluster mode enabled, it cannot be disabled without first destroying and redeploying

## references
- Closes #180

### CODE REVIEW

**Comment by DefinitelyNotBen** [comment]
@milldr Could we get these changes rebased onto the main branch and merged in? Already tested your changes on my own fork and works great!

**Review by dudymas — APPROVED** [review]
lgtm

**Pull request merged**
