### PR TITLE
fix alarm metric dimension CacheClusterId

### LINKED ISSUE #56: Cloudwatch alarms insufficient data
I've created a redis without enabling the automatic_failover, only one node. The problem is that alarms at cloudwatch shows insufficient data.
The configured dimension value for CacheClusterId in the alarm is "myredis" and if I see in cloudwatch the current metrics having data are in dimension value "myredis-001".

### PR DESCRIPTION
**Pull request by chelomontilla**
## what
- Update CacheClusterId dimension of the alarms

## why
- The current dimension doesn't match the right cluster id

## references
* Closes https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/56

### CODE REVIEW

**Review by maximmi — DISMISSED** [review]
@chelomontilla please, try to provide `CacheNodeId` dimension as well as stated in documentation [here](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/CacheMetrics.DimensionsAndSets.html) and see if it will help.

**Comment by chelomontilla** [comment]
@maximmi I did an aws elasticache describe-cache-clusters and the output doesn't display any CacheNodeId. 
Here the output:
```
{
   "CacheClusterId":"my-cluster-cache-001",
   "ReplicationGroupId":"my-cluster-cache",
   "CacheClusterStatus":"available",
   "SnapshotRetentionLimit":0,
   "ClientDownloadLandingPage":"https://console.aws.amazon.com/elasticache/home#client-download:",
   "PendingModifiedValues":{

   },
   "Engine":"redis",
   "CacheSecurityGroups":[

   ],
   "NumCacheNodes":1,
   "AuthTokenLastModifiedDate":"2020-02-24T08:35:42.379Z",
   "AutoMinorVersionUpgrade":true,
   "TransitEncryptionEnabled":true,
   "SecurityGroups":[
      {
         "Status":"active",
         "SecurityGroupId":"sg-xxxxxxxx"
      }
   ],
   "CacheNodeType":"cache.t2.small",
   "PreferredMaintenanceWindow":"wed:03:00-wed:04:00",
   "CacheSubnetGroupName":"my-cluster-cache",
   "AuthTokenEnabled":true,
   "AtRestEncryptionEnabled":false,
   "EngineVersion":"5.0.6",
   "CacheClusterCreateTime":"2020-01-15T11:55:02.665Z",
   "PreferredAvailabilityZone":"eu-west-1a",
   "SnapshotWindow":"06:30-07:30",
   "NotificationConfiguration":{
      "TopicStatus":"active",
      "TopicArn":"arn:aws:sns:eu-west-1:xxxxxxxxxxx:xxxxxxxxxxxxxxxxxxx"
   },
   "CacheParameterGroup":{
      "CacheNodeIdsToReboot":[

      ],
      "CacheParameterGroupName":"my-cluster-cache",
      "ParameterApplyStatus":"in-sync"
   }
}
````

**Comment by jamengual** [comment]
@chelomontilla can you rebase from master, please?

**Comment by nitrocode** [comment]
Looks like this was fixed by a previous PR.

**Pull request closed without merging**
