### PR TITLE
fix: add suffix the parameter group

### LINKED ISSUE #142: v0.41.3: Unable to apply new Parameter Group with existing resources
## Describe the Bug
The changes done in v0.41.3 (#141) causes issues with existing resources. 
Since it re-uses the same name Terraform will try to remove it. But since it is in use, it will fail:

```
│ Error: error deleting ElastiCache Parameter Group (PROJECT-staging-redis): InvalidCacheParameterGroupState: One or more cache clusters are still members of this parameter group PROJECT-staging-redis, so the group cannot be deleted.
│ 	status code: 400, request id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

## Expected Behavior
No errors when applying changes.

## Potential solution
* The parameter group needs to be `create_before_destroy`
* A unique name should be used. In the RDS module we can use `name_prefix` for a similar issue but unfortunately the [aws_elasticache_parameter_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_parameter_group) resource does not support this.

If this is not possible we can work around this by making the description of the parameter group configurable, so that the `Managed by Terraform` value can be used for existing resources.

### PR DESCRIPTION
**Pull request by syphernl**
## what
* Added a generated suffix to the ElastiCache Redis Parameter Group name
* Added `create_before_destroy` ensuring a new PG is created _before_ destroying the existing one

## why
* Elasticache Redis Parameter Groups cannot modify their `description` without recreation. If a PG already existed, it could not be updated/replaced. 
* The Parameter Group will automatically be recreated when the ``description` or the `family` changes

## references
* Closes #142
* Relates to #143

### CODE REVIEW

**Comment by simoferr98** [comment]
Hi @syphernl  I noticed this problem and I was about to open a new pull request.

The name of the resource aws_elasticache_parameter_group I would have indicated it like this:

`  name        = "${module.this.id}-${random_id.redis_pg_name[0].hex}"`

to keep the same name on the various resources. 

Can you implement this change?

**Comment by syphernl** [comment]
> Hi @syphernl I noticed this problem and I was about to open a new pull request.
> 
> The name of the resource aws_elasticache_parameter_group I would have indicated it like this:
> 
> ` name = "${module.this.id}-${random_id.redis_pg_name[0].hex}"`
> 
> to keep the same name on the various resources.
> 
> Can you implement this change?

The `prefix` argument ([docs](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id#optional)) of the `random_id` resource _should_ take care of that: https://github.com/cloudposse/terraform-aws-elasticache-redis/pull/144/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR101.
The generated name should return something like `myproject-stage-redis-hex`, which would only change again in case the description or family does.

**Comment by simoferr98** [comment]
Hi @syphernl ,
Thanks for the clarification. I approve your changes

**Comment by nitrocode** [comment]
@syphernl is this still needed?

**Comment by syphernl** [comment]
No, we can close this one in favor of #143.

**Pull request closed without merging**
