### PR TITLE
Fix creation of Redis in cluster mode

### PR DESCRIPTION
**Pull request by samsullivan**
## what
* fix creation on `cluster_mode_enabled`
* don't send `number_cache_clusters` or `availability_zones` for cluster mode

## why
* neither parameter are supported for cluster mode; more info:
  * [`number_cache_clusters`](https://github.com/terraform-providers/terraform-provider-aws/issues/10458#issuecomment-549522250)
  * [`availability_zones`](https://github.com/terraform-providers/terraform-provider-aws/issues/5104#issuecomment-403123630)

## references
* fixes https://github.com/cloudposse/terraform-aws-elasticache-redis/issues/64

### CODE REVIEW

**Comment by dilsilva** [comment]
This PR merge will be very appreciated :B

**Comment by samsullivan** [comment]
Awesome, thanks!

**Comment by samsullivan** [comment]
No problem, appreciate it getting merged.

**Pull request merged**
