### PR TITLE
add and document variable for missing data in alarms

### LINKED ISSUE #56: Cloudwatch alarms insufficient data
I've created a redis without enabling the automatic_failover, only one node. The problem is that alarms at cloudwatch shows insufficient data.
The configured dimension value for CacheClusterId in the alarm is "myredis" and if I see in cloudwatch the current metrics having data are in dimension value "myredis-001".

### PR DESCRIPTION
**Pull request by chrischildresssg**
## what
* Added logic to handle missing data points in CloudWatch metrics alarms

## why
* Without this functionality, alarms created with this module may show up as "insufficient data" and act as such, neither being in "alarm" or "ok" state.

## references
* `closes #56`

### CODE REVIEW

**Comment by jamengual** [comment]
@chrischildresssg could you rebase from master plase? thanks

**Comment by chrischildresssg** [comment]
> @chrischildresssg could you rebase from master plase? thanks

I apologize; I'm not sure what you want.

**Comment by jamengual** [comment]
There is conflicts that need to get fixed @chrischildresssg  if you pull from master and solve the conflicts we will be able to run tests

**Comment by aknysh** [comment]
@chrischildresssg please rebase

**Review by jamengual — APPROVED** [review]

**Comment by jamengual** [comment]
@chrischildresssg could please fix the conflict ?

**Comment by jamengual** [comment]
@chrischildresssg is this still relevant?

**Comment by chrischildresssg** [comment]
I'm going to close this PR; I do not believe it is still necessary. I apologize if there have been any issues caused by it.

**Pull request closed without merging**
